# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-04 08:09
from __future__ import unicode_literals

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to=course.models.user_directory_path),
        ),
    ]
