# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-25 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleModel',
            new_name='ArticleColumn',
        ),
    ]
