# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-20 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticles',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='blogarticles',
            old_name='publisher',
            new_name='publish',
        ),
    ]
